// Code generated by go generate; DO NOT EDIT.
package test

import "github.com/Shopify/go-lua"

func LuaTest(l *lua.State) int {
	a1 := lua.CheckString(l, 1)
	a2 := lua.CheckString(l, 2)
	o1, err := Test(a1, a2)
	if err != nil {
		l.PushString(err.Error())
		l.Error()
		return 0
	}
	l.PushString(o1)
	return 1
}
